services:
  client:
    build: client/
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/App
      - /App/node_modules

  client2:
    build: client/
    ports:
      - "3001:3000"
    depends_on:
      - server
    volumes:
      - ./client:/App
      - /App/node_modules

  server:
    build: server/
    ports:
      - "4000:4000"
    volumes:
      - ./server:/App
      - /App/node_modules
