services:

  client:
    build: client/
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - socket-server
    volumes:
      - ./client:/App
      - /App/node_modules

  socket-server:
    build: server/socket-server/
    ports:
      - "4000:4000"
    depends_on:
      - rest-server
    volumes:
      - ./server/socket-server:/App
      - /App/node_modules

  rest-server:
    build: server/rest-server/
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./server/rest-server:/App

  postgres:
    image: postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    expose:
      - "6379"
    volumes:
      - ./configs/redis.conf:/etc/redis/redis.conf

volumes:
  pgdata:
